### ISSUE TITLE
Отображение занятий, поставленных без перерыва

### ISSUE THREAD

**Issue by vitta** [h4/unischedule#69]
![image](https://cloud.githubusercontent.com/assets/2279586/5525938/082f93ac-89ff-11e4-9cba-95099052596c.png)
Если занятия поставлены с 10 до 12 и с 12 до 14, то отображаются без разрыва, что логично, но у первого по времени занятия скрывается блок с местом проведения занятия. 
![image](https://cloud.githubusercontent.com/assets/2279586/5525962/5fd18322-89ff-11e4-896e-4d05329a4ddf.png)

**Comment by h4** [comment]
Теперь справа выводится время. Этого достаточно?
