### ISSUE TITLE
Добавить сетку пар (линии) по горизонтали и/или время внутри прямоугольника занятия

### ISSUE THREAD

**Issue by vitta** [h4/unischedule#72]
Миша, рассмотри возможность, добавления:
 - времени начала и окончания занятия внутри прямоугольника занятия (так как это сделано у САфу)
![image](https://cloud.githubusercontent.com/assets/2279586/6777366/31d4db3e-d15a-11e4-9d50-c29fead21132.png)
 - горизонтальных линий сетки (только 10, 12, 14, 16, 18)

По мне так первого будет достаточно.

**Comment by vitta** [comment]
Миша, есть шанс, что появится на это время?

**Comment by h4** [comment]
@vitta ага, сделаю.

**Comment by h4** [comment]
Fixed
