### ISSUE TITLE
Добавить четная/нечетная неделя рядом с текущим временм

### ISSUE THREAD

**Issue by vitta** [h4/unischedule#73]
![image](https://cloud.githubusercontent.com/assets/2279586/6777423/a72959b4-d15a-11e4-8900-79c1e847bb46.png)
С текущего размещения убрать.

**Comment by h4** [comment]
@ftomza сделай мне ручку `/info`, которая будет отдавать json вида
```json
{
    "is_odd_week": true
}
```
true — для нечётной, false для чётной.

**Comment by ftomza** [comment]
@h4 Готово

**Comment by h4** [comment]
@vitta так ведь фигня получится, если с текущего размещения убрать.

Под часами ожидаемо видеть какая неделя сейчас.
В заголовке страницы — к какой неделе относится страница.

Может не будем убирать с текущего места расположения.
