### ISSUE TITLE
Разместить ссылку на сайт Политеха

### ISSUE THREAD

**Issue by vitta** [h4/unischedule#76]
Миша, куда можно ссылку на http://www.spbstu.ru/ разместить? требуют от нас :(

**Comment by h4** [comment]
@vitta можно подвал чуть повыше сделать и снизу запихать.

**Comment by h4** [comment]
@ftomza нужно пересобрать фронтенд.

**Comment by ftomza** [comment]
В режиме киоска думаю нужно убрать, а то перейдут на сайт, а обратно то как?
