### ISSUE TITLE
Некорректно отображаются блоки занятий по подгруппам в случае, если время начала и окончания этих занятий разное

### ISSUE THREAD

**Issue by vitta** [h4/unischedule#79]
Пример:
![20150706-1](https://cloud.githubusercontent.com/assets/2279586/8544598/451a01d0-24af-11e5-8d1a-fbfd8db57a48.png)
![20150706-2](https://cloud.githubusercontent.com/assets/2279586/8544602/46d4bc22-24af-11e5-8055-df64b7eb8a63.png)
http://ruz.spbstu.ru/#/schedule/19948?date=2015-08-31 
Как исправить пока не знаю.

**Comment by vitta** [comment]
Пример с проблемным отображением пар есть по ссылкам:
http://ruz.spbstu.ru/#/schedule/19948?date=2015-08-31 
http://ruz.spbstu.ru/#/schedule/19185?date=2015-09-07 (понедельник)

**Comment by vitta** [comment]
Вот здесь хорошо видно http://ruz.spbstu.ru/#/schedule/19155?date=2015-08-31

Можно сделать так, чтобы занятия в четверг отображались также, как и во вторник в примере по ссылке? т.е. чтобы эти блоки вели себя как занятия по подгруппам, начинающиеся в одно время?

**Comment by vitta** [comment]
http://ruz.spbstu.ru/#/schedule/19170 Четверг
доп. главы теор. физики  12-15 и Физическая кристаллография 15-17:30
При первом заходе:
![image](https://cloud.githubusercontent.com/assets/2279586/9598361/5231986e-5093-11e5-911b-6d50889d76b9.png)
После выбора Доп. глав блок "прилипает" и больше не отлипает:
![image](https://cloud.githubusercontent.com/assets/2279586/9598396/d228a260-5093-11e5-90fc-3bdb05c91a83.png)

**Comment by h4** [comment]
Чьорт, не сложилось ;) Мой костылик ожидал, что будет только два занятия с перекрытием. Карочи надо уже сделать всё по честному.
