### ISSUE TITLE
Четная/нечетная недели

### ISSUE THREAD

**Issue by vitta** [h4/unischedule#80]
Первая неделя семестра с 1 сентября является не четной. Сейчас неделя с 31 августа отображается как четная http://ruz.spbstu.ru/#/schedule/19672?date=2015-08-31. У нас признак четности недели ведь не передается веб-сервисом?

**Comment by h4** [comment]
Как раз наоборот. Это параметр `week.is_odd`.

![2015-08-19 12-56-00](https://cloud.githubusercontent.com/assets/430023/9353497/8514662a-4671-11e5-990a-c7ed137e5f05.png)

**Comment by vitta** [comment]
Хм, значит определяется у Темы не правильно. Скорее всего эта неделя является четной, если считать с начала календарного года, но для расписания неделя с 1 сентября - всегда первая и нечетная.

**Comment by h4** [comment]
Поменял.

@ftomza я там запилил отдельный репозиторий в битбакете, как копию твоего. Приедешь — звони, расскажу что там да как.

**Comment by ftomza** [comment]
@h4 @vitta у нас же эта перда подпоркой регулируется. Если есть мысли как это сделать, то велкам. Хранить это в виде настройки есть проблема, так как нет постоянного хранилища и приложение распределенное.

**Comment by vitta** [comment]
А можно еще раз подпорку подпереть и сделать, чтобы неделя с 31 августа была нечетной? Сейчас все недели стали четными.

**Comment by h4** [comment]
Стопе. Все чётные — это то, что под часами написано? Так это какая неделя сейчас — чётная или нечётная. Я уже не помню, зачем её туда запихали.

@ftomza ты глянь в код-то. Там щас всё безо всяких подпорок, чистая математика.

**Comment by h4** [comment]
@vitta @ftomza в общем, чётная и нечётная неделя под часами появятся с началом семестра. Потому что в период сессии и каникул этот параметр вообще не имеет смысла.
